import React, { useEffect, useState } from 'react'
import { ArrowDown, ArrowUpRight, Check, Menu, Search, ShoppingBag, X } from 'lucide-react'
import './styles.css'
import './collage.css'
import './store.css'
import './store-collage.css'
import './store-spread.css'
import './store-fan.css'
import './store-index.css'
import './item-page.css'

const products = [
  { name: 'Cloud Nest', type: 'Sleep / 01', price: '$128', category: 'Sleep', image: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&w=1200&q=90' },
  { name: 'Moss Bowl', type: 'Feed / 02', price: '$64', category: 'Feed', image: 'https://images.unsplash.com/photo-1560743641-3914f2c45636?auto=format&fit=crop&w=1200&q=90' },
  { name: 'Loop Lead', type: 'Walk / 03', price: '$42', category: 'Walk', image: 'https://images.unsplash.com/photo-1558929996-da64ba858215?auto=format&fit=crop&w=1200&q=90' },
  { name: 'Sunbeam Toy', type: 'Play / 04', price: '$28', category: 'Play', image: 'https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?auto=format&fit=crop&w=1200&q=90' },
  { name: 'Trail Towel', type: 'Walk / 05', price: '$36', category: 'Walk', image: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&w=1200&q=90' },
]
const productSlug = (product) => product.name.toLowerCase().replaceAll(' ', '-')
window.addEventListener('click', (event) => { const card = event.target.closest?.('.collage-card'); if (card?.getAttribute('href')?.startsWith('#')) window.location.hash = card.getAttribute('href').slice(1) })

function Header({ bagCount, onMenu, onSearch }) { return <header className="header"><a className="logo" href="#top">cairn<span>/04</span></a><nav><a href="#/store">Store</a><a href="#top">Field notes</a><a href="#about">About</a></nav><div className="header-tools"><button aria-label="Search" onClick={onSearch}><Search size={17} /></button><button aria-label="Shopping bag"><ShoppingBag size={17} /><b>{bagCount}</b></button><button className="menu-button" onClick={onMenu} aria-label="Open menu"><Menu size={18} /></button></div></header> }

function FocalHero() {
  const [progress, setProgress] = useState(0)
  useEffect(() => { const update = () => setProgress(Math.min(1, Math.max(0, window.scrollY / (window.innerHeight * .9)))); addEventListener('scroll', update, { passive: true }); update(); return () => removeEventListener('scroll', update) }, [])
  const product = products[0]
  const photographs = [
    { image: products[0].image, name: 'Daily rituals', detail: '01 / daily rituals', description: 'Small routines become the good part of the day.' },
    { image: products[1].image, name: 'Natural materials', detail: '02 / natural materials', description: 'Honest textures chosen to age with the room.' },
    { image: products[2].image, name: 'Made for outside', detail: '03 / made for outside', description: 'Ready for open doors, long walks, and weather.' },
    { image: products[3].image, name: 'Quiet function', detail: '04 / quiet function', description: 'Useful forms that do their work without noise.' },
    { image: products[4].image, name: 'A life together', detail: '05 / a life together', description: 'Objects designed around the companionship we share.' },
  ]
  return <section className="focal-hero" id="top" style={{ '--focal-progress': progress }}><div className="focal-backdrop" /><div className="focal-shell"><div className="focal-side focal-left"><p>Objects for a life together</p><h1>Made to<br /><i>matter.</i></h1><span>01 / 05</span></div><div className="focal-center"><div className="focus-ring" /><div className="focal-stack">{photographs.map((photo, index) => <div className={`stack-photo stack-photo-${index}`} key={photo.name} style={{ '--photo-index': index }}><img src={photo.image} alt={photo.name} /><span>{photo.detail}</span><em>{photo.description}</em></div>)}</div></div><div className="focal-side focal-right"><p>Quiet function<br />considered form</p><div><span>Scroll once to unravel</span><ArrowDown size={16} /></div><span className="coordinates">34° 08′ / cairn field</span></div></div><div className="focal-progress">0{Math.round(progress * 100)}<span>%</span></div><div className="focal-instruction">A study of the life around us</div></section>
}

function ProductCard({ product, onAdd }) { return <article className="product-card"><a href={`#${product.name.toLowerCase().replaceAll(' ', '-')}`} className="product-image"><img src={product.image} alt={product.name} /><span>View piece <ArrowUpRight size={15} /></span></a><div className="product-meta"><div><small>{product.type}</small><h3>{product.name}</h3></div><strong>{product.price}</strong></div><button className="add-button" onClick={() => onAdd(product)}>Add to bag <ArrowUpRight size={15} /></button></article> }

function Collection({ onAdd }) { const [filter, setFilter] = useState('All'); const categories = ['All', 'Sleep', 'Walk', 'Feed', 'Play']; const visible = products.filter((product) => filter === 'All' || product.category === filter); return <section className="collection" id="collection"><div className="collection-intro"><p className="eyebrow">The collection / 04</p><h2>Keep what<br /><i>matters.</i></h2><p>A restrained edit of useful objects for the rituals that make a shared life feel good.</p></div><div className="collection-tools"><span>05 pieces / 2025</span><div>{categories.map((category) => <button className={filter === category ? 'selected' : ''} key={category} onClick={() => setFilter(category)}>{category}</button>)}</div></div><div className="product-grid">{visible.map((product) => <ProductCard product={product} onAdd={onAdd} key={product.name} />)}</div></section> }

function Store() { const [filter, setFilter] = useState('All'); const [query, setQuery] = useState(''); const [activeProduct, setActiveProduct] = useState(null); const categories = ['All', 'Sleep', 'Walk', 'Feed', 'Play']; const visible = products.filter((product) => (filter === 'All' || product.category === filter) && `${product.name} ${product.type} ${product.category}`.toLowerCase().includes(query.toLowerCase().trim())); const activeIndex = activeProduct === null || activeProduct >= visible.length ? 0 : activeProduct; const spreadStart = Math.max(24, (1180 - ((visible.length - 1) * 105 + 250)) / 2); return <section className="store-page"><div className="store-heading"><div><p className="eyebrow">The cairn store / 04</p><h1>Find a piece<br /><i>to live with.</i></h1></div><p>Browse the collection as a loose arrangement. Hover an exposed photograph to reveal and select its piece.</p><a href="#top"><ArrowUpRight size={15} /> Back to the focus</a></div><div className="store-tools"><span>{String(visible.length).padStart(2, '0')} photographs / collage field</span><div className="store-filters"><label className="store-search"><Search size={14} /><input id="store-search" type="search" value={query} onChange={(event) => { setQuery(event.target.value); setActiveProduct(null) }} placeholder="Search pieces" aria-label="Search pieces" /></label>{categories.map((category) => <button className={filter === category ? 'selected' : ''} key={category} onClick={() => { setFilter(category); setActiveProduct(null) }}>{category}</button>)}</div></div><div className="store-spread"><aside className="store-index" aria-label="Collection index"><span className="index-label">Index / 04</span>{visible.map((product, index) => <button className={`index-handle ${activeIndex === index ? 'active' : ''}`} key={product.name} onMouseEnter={() => setActiveProduct(index)} onFocus={() => setActiveProduct(index)} onMouseLeave={() => setActiveProduct(null)} onBlur={() => setActiveProduct(null)}><span>{String(index + 1).padStart(2, '0')}</span><strong>{product.name}</strong><small>{product.type}</small></button>)}</aside><div className="store-collage" style={{ '--card-count': visible.length, '--spread-start': `${spreadStart}px` }}>{visible.map((product, index) => <a href={`#${productSlug(product)}`} className={`collage-card collage-card-${index} ${activeIndex === index ? 'active' : ''}`} style={{ '--card-index': index }} key={product.name} onClick={(event) => { event.preventDefault(); setActiveProduct(index) }} onMouseEnter={() => setActiveProduct(index)} onMouseLeave={() => setActiveProduct(null)} onFocus={() => setActiveProduct(index)} onBlur={() => setActiveProduct(null)}><img src={product.image} alt={product.name} /><span><strong>{product.name}</strong><small>{product.type}</small></span></a>)}<div className="collage-note"><span>Field arrangement / 04</span><strong>Objects<br /><i>in orbit.</i></strong></div></div></div></section> }

function ItemPage({ product }) { const [drawerOpen, setDrawerOpen] = useState(true); const strip = [...products, ...products, ...products]; return <main className="item-page"><div className="item-intro"><a href="#/store"><ArrowUpRight size={15} /> Back to the spread</a><span>Piece / {product.type}</span></div><div className="film-field"><div className="film-strip film-strip-top">{strip.map((item, index) => <a href={`#${productSlug(item)}`} className={item.name === product.name ? 'film-frame selected' : 'film-frame'} key={`top-${index}`}><img src={item.image} alt={item.name} /><small>{item.type}</small></a>)}</div><div className="film-mark">Cairn / {productSlug(product)}</div><div className="film-strip film-strip-bottom">{[...strip].reverse().map((item, index) => <a href={`#${productSlug(item)}`} className={item.name === product.name ? 'film-frame selected' : 'film-frame'} key={`bottom-${index}`}><img src={item.image} alt={item.name} /><small>{item.type}</small></a>)}</div></div><button className="item-drawer-toggle" onClick={() => setDrawerOpen(!drawerOpen)} aria-expanded={drawerOpen}> {drawerOpen ? <X size={16} /> : <ArrowUpRight size={16} />} <span>{drawerOpen ? 'Close details' : 'View details'}</span></button><aside className={`item-drawer ${drawerOpen ? 'open' : ''}`}><div className="drawer-kicker">Selected piece / 04</div><div><p className="eyebrow">{product.type}</p><h1>{product.name}</h1><p className="drawer-description">An considered object for the rituals that make a shared life feel good. Quietly useful, made to stay close.</p></div><div className="drawer-footer"><strong>{product.price}</strong><button>Add to bag <ArrowUpRight size={15} /></button><span>Ships in 2-4 working days</span></div></aside></main> }

function Story() { return <section className="story" id="story"><p className="eyebrow">Field note / 01</p><h2>The quiet<br /><i>good stuff.</i></h2><p>Less noise, more intention. We choose materials and forms that become part of the room instead of asking to own it.</p><a href="#about">Read our approach <ArrowUpRight size={15} /></a></section> }

function App() { const [bagCount] = useState(0); const [menuOpen, setMenuOpen] = useState(false); const [hash, setHash] = useState(window.location.hash); useEffect(() => { const update = () => setHash(window.location.hash); addEventListener('hashchange', update); return () => removeEventListener('hashchange', update) }, []); const storeRoute = hash === '#/store'; const itemProduct = products.find((product) => `#${productSlug(product)}` === hash); return <div><Header bagCount={bagCount} onSearch={() => document.getElementById('store-search')?.focus()} onMenu={() => setMenuOpen(true)} />{itemProduct ? <ItemPage product={itemProduct} /> : storeRoute ? <Store /> : <FocalHero />}{menuOpen && <div className="menu-drawer"><button onClick={() => setMenuOpen(false)} aria-label="Close menu"><X /></button><nav><a href="#/store" onClick={() => setMenuOpen(false)}>Store</a><a href="#top" onClick={() => setMenuOpen(false)}>Beginning</a><a href="#top" onClick={() => setMenuOpen(false)}>About</a></nav></div>}</div> }

import { createRoot } from 'react-dom/client'
createRoot(document.getElementById('root')).render(<App />)
