import { useEffect, useState } from 'react'
import { BrowserRouter, Link, NavLink, Route, Routes, useLocation } from 'react-router-dom'
import { ArrowRight, Check, ChevronLeft, ChevronRight, Crosshair, FileText, MapPin, Menu, Play, Radio, Shield, ShieldCheck, Star, Target, Users, X } from 'lucide-react'
import './App.css'
import './hero-overrides.css'

const images = {
  hero: 'https://images.unsplash.com/photo-1560253023-3ec5d502959f?auto=format&fit=crop&w=1800&q=85',
  command: 'https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1200&q=80',
  cctv: 'https://images.unsplash.com/photo-1557597774-9d273605dfa9?auto=format&fit=crop&w=1000&q=80',
  team: 'https://images.unsplash.com/photo-1581092795360-fd1ca04f0952?auto=format&fit=crop&w=1000&q=80',
  guard: 'https://images.unsplash.com/photo-1511497584788-876760111969?auto=format&fit=crop&w=1000&q=80',
  city: 'https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?auto=format&fit=crop&w=1600&q=80',
  community: 'https://images.unsplash.com/photo-1532629345422-7515f3d16bb6?auto=format&fit=crop&w=1600&q=80',
}
const services = [
  { title: 'Armed Guarding', icon: Shield, tag: '24 / 7 COVERAGE', image: images.guard, text: 'Disciplined, licensed security officers trained to protect your sites, people and assets with calm precision.', detail: 'Our guarding teams combine close observation, clear escalation protocols and visible presence. Each deployment is built around your risk profile, from executive residences to logistics hubs.', items: ['Licensed and bonded personnel', 'Post orders and daily reporting', 'Rapid escalation command line'] },
  { title: 'Executive Protection', icon: Target, tag: 'LOW PROFILE. HIGH READINESS.', image: images.team, text: 'Intelligent close protection for executives, families and high-value movements across the Philippines.', detail: 'Protection starts before the principal arrives. Our advance teams map routes, venues and contingencies so movement remains discreet and uninterrupted.', items: ['Advance threat assessment', 'Secure transport coordination', 'Protective intelligence briefings'] },
  { title: 'Command & CCTV', icon: Radio, tag: 'LIVE INTELLIGENCE', image: images.cctv, text: 'Always-on monitoring and incident response from a centralized command environment.', detail: 'Our control room turns cameras, access systems and field reports into a single operating picture. Alerts are verified quickly and routed to the right response team.', items: ['Remote video monitoring', 'Incident verification and dispatch', 'Monthly system health audits'] },
  { title: 'Event Security', icon: Users, tag: 'SEAMLESS CONTROL', image: images.command, text: 'Guest-first security planning for corporate events, public gatherings and high-profile occasions.', detail: 'We secure the experience without getting in its way. From ingress planning to emergency lanes, our event teams make complex movement feel natural.', items: ['Venue and crowd risk plans', 'Guest screening and access control', 'Dedicated event commander'] },
  { title: 'K9 Detection', icon: Crosshair, tag: 'SPECIALIST TEAMS', image: images.city, text: 'Specialist canine teams for detection, deterrence and sensitive-site sweeps.', detail: 'Our handler-and-canine units are deployed for pre-event sweeps, contraband detection and perimeter assurance where human senses are not enough.', items: ['Certified handlers', 'Pre-event and route sweeps', 'Flexible rapid deployment'] },
  { title: 'Risk Advisory', icon: FileText, tag: 'DECISIONS WITH CLARITY', image: images.hero, text: 'Practical risk intelligence that makes your people, property and plans more resilient.', detail: 'We translate exposure into action: site surveys, vulnerability reviews, travel briefs and operating playbooks for leadership teams.', items: ['Site vulnerability reviews', 'Crisis readiness workshops', 'Executive travel intelligence'] },
]
const jobs = [
  { title: 'Security Officer', location: 'Makati · Full time', salary: 'PHP 22,000 – 28,000', type: 'FIELD OPERATIONS', requirements: ['At least 2 years of licensed security experience', 'Valid License to Exercise Security Profession', 'Physically fit with clear incident reporting skills'] },
  { title: 'VIP Chauffeur', location: 'Metro Manila · Full time', salary: 'PHP 28,000 – 35,000', type: 'PROTECTIVE MOBILITY', requirements: ['Professional Driver license with clean record', 'Defensive driving certification preferred', 'Discretion, punctuality and route familiarity'] },
  { title: 'Control Room Monitor', location: 'BGC · Rotating shifts', salary: 'PHP 24,000 – 30,000', type: 'COMMAND CENTER', requirements: ['Experience with CCTV or access control systems', 'Strong attention to detail', 'Comfortable with rotating day and night shifts'] },
  { title: 'Field Inspector', location: 'Luzon · Full time', salary: 'PHP 30,000 – 40,000', type: 'QUALITY ASSURANCE', requirements: ['5+ years in security operations', 'Strong coaching and documentation ability', 'Willingness to travel between client sites'] },
]
const navItems = [['Services', '/services'], ['About us', '/about'], ['Careers', '/careers'], ['Newsroom', '/news'], ['Clients', '/clients']]

function App() {
  const location = useLocation()
  useEffect(() => { document.body.classList.toggle('about-mode', location.pathname === '/about'); window.scrollTo({ top: 0, behavior: 'instant' }); return () => document.body.classList.remove('about-mode') }, [location.pathname])
  return <div className="app-shell"><Header /><main><Routes><Route path="/" element={<Home />} /><Route path="/services" element={<Services />} /><Route path="/about" element={<About />} /><Route path="/careers" element={<Careers />} /><Route path="/news" element={<News />} /><Route path="/contact" element={<Contact />} /><Route path="/clients" element={<Clients />} /><Route path="/donations" element={<Donations />} /></Routes></main><Footer /></div>
}
function Header() { const [open, setOpen] = useState(false); return <header className="site-header"><Link to="/" className="brand"><span className="brand-mark"><img src="https://www.soliman-security.com/img/logo.png" alt="Soliman Security logo" /></span><span><b>SOLIMAN</b><small>SECURITY</small></span></Link><nav className={open ? 'nav-open' : ''}>{navItems.map(([label, path]) => <NavLink key={path} to={path} onClick={() => setOpen(false)}>{label}</NavLink>)}<Link className="nav-cta" to="/contact" onClick={() => setOpen(false)}>Request a consultation <ArrowRight size={15} /></Link></nav><button className="menu-btn" onClick={() => setOpen(!open)} aria-label="Toggle menu">{open ? <X /> : <Menu />}</button></header> }
function Eyebrow({ children }) { return <div className="eyebrow"><span />{children}</div> }
function PageIntro({ eyebrow, title, copy }) { return <section className="page-intro wrap"><div><Eyebrow>{eyebrow}</Eyebrow><h1>{title}</h1></div>{copy && <p>{copy}</p>}</section> }
function Button({ to, children, secondary = false }) { return <Link className={`button ${secondary ? 'button-secondary' : ''}`} to={to}>{children}<ArrowRight size={16} /></Link> }
function Home() { const [blend, setBlend] = useState('overlay'); return <><section className="hero"><div className="hero-grid">{Array.from({ length: 900 }, (_, index) => [images.hero, images.cctv, images.team, images.guard, images.command, images.city, images.community][index % 7]).map((src, i) => <div key={`${src}-${i}`} className={`hero-tile tile-${i}`} style={{ backgroundImage: `url(${src})`, '--tile-row-delay': `${0.18 + Math.floor(i / 30) * 0.12}s` }} />)}</div><div className={`flag-overlay blend-${blend}`} /><div className="hero-content wrap"><Eyebrow>PHILIPPINES · EST. 1998</Eyebrow><h1>Security with<br /><em>conviction.</em></h1><p>Protecting what matters with the discipline, intelligence and human care that modern security demands.</p><div className="hero-actions"><Button to="/services">Explore our services</Button><Button to="/contact" secondary>Start a conversation</Button></div></div><div className="hero-meta"><span>01 / 03</span><span className="hero-line" /><span>BUILT FOR THE MOMENT</span></div><div className="blend-control"><span>IMAGE TREATMENT</span>{['overlay', 'multiply'].map(option => <button className={blend === option ? 'active' : ''} onClick={() => setBlend(option)} key={option}>{option}</button>)}</div></section><section className="statement wrap reveal"><div className="stat-number">01</div><div><Eyebrow>THE SOLIMON STANDARD</Eyebrow><h2>Confidence is a feeling.<br /><span>We make it a system.</span></h2></div><div className="statement-copy"><p>Across every watch, escort and response, our people bring an uncommon standard of readiness. You get a partner who sees around corners and stands steady when it matters.</p><Link to="/about" className="text-link">Meet Solimon <ArrowRight size={16} /></Link></div></section><section className="home-band"><div className="wrap service-tease"><div><Eyebrow>OUR CAPABILITIES</Eyebrow><h2>One command.<br />Every layer protected.</h2></div><div className="tease-list">{services.slice(0, 3).map((service, i) => <Link to="/services" className="tease-item" key={service.title}><span>0{i + 1}</span><b>{service.title}</b><ArrowRight size={17} /></Link>)}</div></div></section></> }
function Services() { const [selected, setSelected] = useState(null); return <><PageIntro eyebrow="CAPABILITIES" title={<>Security that moves<br /><em>with your world.</em></>} copy="From a single site to a national footprint, Solimon brings specialized people, intelligence and technology together under one accountable command." /><section className="wrap services-grid">{services.map((service, i) => <article className="service-card reveal" key={service.title} onClick={() => setSelected(service)}><div className="card-image" style={{ backgroundImage: `url(${service.image})` }}><span>{service.tag}</span><service.icon size={23} /></div><div className="card-body"><span>0{i + 1}</span><h3>{service.title}</h3><p>{service.text}</p><button className="text-link">View scope <ArrowRight size={15} /></button></div></article>)}</section>{selected && <ServiceModal service={selected} close={() => setSelected(null)} />}</> }
function ServiceModal({ service, close }) { return <div className="modal-backdrop" onClick={close}><div className="modal" onClick={e => e.stopPropagation()}><button className="modal-close" onClick={close} aria-label="Close"><X /></button><div className="modal-image" style={{ backgroundImage: `url(${service.image})` }}><span>{service.tag}</span><h2>{service.title}</h2></div><div className="modal-content"><p className="modal-lede">{service.detail}</p><div className="modal-columns"><div><span className="label">SCOPE OF WORK</span><ul>{service.items.map(item => <li key={item}><Check size={15} />{item}</li>)}</ul></div><div><span className="label">DEPLOYMENT NOTE</span><p>Every Solimon assignment starts with a site briefing and ends with measurable reporting. Personnel, equipment and escalation paths are matched to the risk profile.</p></div></div><Button to="/contact">Request a quote</Button></div></div></div> }
function About() { const [slide, setSlide] = useState(0); const slides = [<div className="about-slide slide-dark"><div className="about-slide-inner wrap"><div><Eyebrow>01 · THE WHY</Eyebrow><h1>Ready for<br /><em>what comes.</em></h1></div><div className="slide-note"><span>OUR MISSION</span><p>To protect people and progress through a higher standard of security: human, intelligent and always prepared.</p><div className="values"><span>DISCIPLINE</span><span>VIGILANCE</span><span>RESPECT</span></div></div></div></div>, <div className="about-slide slide-image" style={{ backgroundImage: `linear-gradient(90deg, rgba(9,13,22,.96) 15%, rgba(9,13,22,.54), rgba(9,13,22,.2)), url(${images.command})` }}><div className="about-slide-inner wrap"><div><Eyebrow>02 · THE JOURNEY</Eyebrow><h2>Built in Manila.<br /><em>Trusted everywhere.</em></h2></div><div className="milestones"><b>1998</b><p>Solimon begins with one team, one city and a promise to do the work properly.</p><b>2012</b><p>National operations expand across Luzon, Visayas and Mindanao.</p><b>2024</b><p>Our command model unites protection, intelligence and technology.</p></div></div></div>, <div className="about-slide slide-light"><div className="about-slide-inner wrap"><div><Eyebrow>03 · THE COMMAND</Eyebrow><h2>One team.<br /><em>Clear lines.</em></h2></div><OrgChart /></div></div>, <div className="about-slide slide-dark"><div className="about-slide-inner wrap"><div><Eyebrow>04 · THE PROOF</Eyebrow><h2>Standards are<br /><em>earned daily.</em></h2></div><div className="accreditations"><div><ShieldCheck size={25} /><b>PNP LICENSED</b><span>License to operate</span></div><div><Star size={25} /><b>ISO ALIGNED</b><span>Quality management</span></div><div><FileText size={25} /><b>DOLE COMPLIANT</b><span>People first practices</span></div></div></div></div>, <div className="about-slide slide-red"><div className="about-slide-inner wrap"><div><Eyebrow>05 · THE PROMISE</Eyebrow><h2>Security that<br /><em>serves society.</em></h2></div><div className="promise"><p>We hold ourselves to Philippine security standards that respect the law, the community and the dignity of every person we protect.</p><Button to="/contact">Work with Solimon</Button></div></div></div>]; return <section className="about-deck" onScroll={e => setSlide(Math.round(e.currentTarget.scrollTop / e.currentTarget.clientHeight))}>{slides.map((content, i) => <div className="slide-wrap" key={i}>{content}</div>)}<div className="slide-pager"><span>ABOUT SOLIMON</span><b>0{slide + 1}</b><span>/ 05</span><div className="pager-dots">{slides.map((_, i) => <i className={i === slide ? 'active' : ''} key={i} />)}</div></div><div className="slide-arrows"><button onClick={() => document.querySelector('.about-deck').scrollBy({ top: -window.innerHeight, behavior: 'smooth' })}><ChevronLeft /></button><button onClick={() => document.querySelector('.about-deck').scrollBy({ top: window.innerHeight, behavior: 'smooth' })}><ChevronRight /></button></div></section> }
function OrgChart() { return <div className="org-chart"><div className="org-node top"><small>EXECUTIVE LEADERSHIP</small><b>Managing Director</b></div><div className="org-connector" /><div className="org-row"><div className="org-node"><small>FIELD OPERATIONS</small><b>Operations Director</b></div><div className="org-node"><small>SPECIAL TEAMS</small><b>Protection Lead</b></div><div className="org-node"><small>INTELLIGENCE</small><b>Command Chief</b></div></div><div className="org-connector" /><div className="org-node bottom"><small>ON-GROUND PERSONNEL</small><b>Section Commanders · Officers · Handlers</b></div></div> }
function Careers() { const [selected, setSelected] = useState(null); return <><PageIntro eyebrow="CAREERS" title={<>The standard starts<br /><em>with our people.</em></>} copy="Join a team trusted with the moments that matter. We invest in clear training, real progression and a culture built on respect." /><section className="careers-intro wrap"><div className="careers-image" style={{ backgroundImage: `url(${images.team})` }} /><div><Eyebrow>WHY SOLIMON</Eyebrow><h2>Do work with<br />weight behind it.</h2><p>Every role carries a clear purpose. You will be equipped, supported and expected to grow into the responsibility.</p><div className="benefit-row"><span><ShieldCheck />Training</span><span><Users />Community</span><span><Star />Progression</span></div></div></section><section className="wrap jobs-section"><div className="section-head"><div><Eyebrow>OPEN POSITIONS</Eyebrow><h2>Find your post.</h2></div><span>04 OPEN ROLES · SEPT 2026</span></div><div className="jobs-list">{jobs.map(job => <article className="job-card" key={job.title} onClick={() => setSelected(job)}><div><span className="label">{job.type}</span><h3>{job.title}</h3><p><MapPin size={14} />{job.location}</p></div><div><b>{job.salary}</b><button className="icon-button"><ArrowRight /></button></div></article>)}</div></section>{selected && <JobModal job={selected} close={() => setSelected(null)} />}</> }
function JobModal({ job, close }) { return <div className="modal-backdrop" onClick={close}><div className="modal job-modal" onClick={e => e.stopPropagation()}><button className="modal-close" onClick={close}><X /></button><div className="modal-content"><span className="label">{job.type}</span><h2>{job.title}</h2><p className="modal-lede">{job.location} · {job.salary}</p><div className="modal-columns"><div><span className="label">WHAT YOU BRING</span><ul>{job.requirements.map(req => <li key={req}><Check size={15} />{req}</li>)}</ul></div><div><span className="label">THE PACKAGE</span><p>HMO coverage, uniform and equipment allowance, paid training, 13th month pay and a clear path to supervisory roles.</p></div></div><form className="apply-form" onSubmit={e => e.preventDefault()}><input placeholder="Full name" /><input placeholder="Email address" type="email" /><label className="upload">Upload resume or license <input type="file" /></label><button className="button" type="submit">Submit application <ArrowRight size={16} /></button></form></div></div></div> }
function News() { const [tag, setTag] = useState('ALL'); const posts = [{ tag: 'INSIGHT', title: 'Five quiet signals that reveal a site is under-protected', author: 'Solimon Intelligence', time: '2h ago', image: images.cctv, avatar: 'FI' }, { tag: 'FIELD NOTES', title: 'Inside the 2026 Solimon readiness exercise', author: 'Mara Santos · Operations', time: '1d ago', image: images.team, avatar: 'MS' }, { tag: 'COMMUNITY', title: 'Building safer routes with our neighborhood partners', author: 'Solimon CSR', time: '4d ago', image: images.community, avatar: 'FC' }]; const filtered = tag === 'ALL' ? posts : posts.filter(post => post.tag === tag); return <><PageIntro eyebrow="NEWSROOM" title={<>Signal over<br /><em>noise.</em></>} copy="Field notes, practical intelligence and updates from the people behind the Solimon standard." /><div className="news-layout wrap"><aside className="news-sidebar"><span className="label">FILTER BY TAG</span>{['ALL', 'INSIGHT', 'FIELD NOTES', 'COMMUNITY'].map(item => <button className={tag === item ? 'active' : ''} onClick={() => setTag(item)} key={item}>{item}<ChevronRight size={14} /></button>)}<div className="trending"><span className="label">TRENDING TIPS</span><p>01 / Make your first response visible.</p><p>02 / Test the quiet hours.</p><p>03 / Name your escalation lead.</p></div></aside><section className="feed">{filtered.map(post => <article className="post reveal" key={post.title}><div className="post-top"><span className="avatar">{post.avatar}</span><div><b>{post.author}</b><small>{post.time} · Public</small></div><span className="label">{post.tag}</span></div><h2>{post.title}</h2><div className="post-image" style={{ backgroundImage: `url(${post.image})` }}><button className="play"><Play size={16} fill="currentColor" /></button></div><div className="post-actions"><button><Star size={16} /> 48</button><button><ArrowRight size={16} /> Share</button><button className="read-more">Read more <ArrowRight size={15} /></button></div></article>)}</section></div></> }
function Contact() { return <><PageIntro eyebrow="CONTACT" title={<>Let's make<br /><em>ready happen.</em></>} copy="Tell us what you are protecting, where you are headed and what keeps you up at night. Our team will come back with a considered first step." /><section className="wrap contact-layout"><div className="contact-details"><div className="map-card"><div className="map-grid" /><div className="map-pin"><MapPin size={22} />SOLIMON HQ</div><span className="map-label">Makati City · 14.5547° N, 121.0244° E</span></div><div className="contact-info"><div><span className="label">EMERGENCY HOTLINE</span><a href="tel:+63288885555">+63 2 8888 5555</a><small>Available 24 hours, 365 days</small></div><div><span className="label">HEAD OFFICE</span><p>18F Meridian Tower<br />Ayala Avenue, Makati City<br />Philippines 1226</p></div><div><span className="label">EMAIL</span><a href="mailto:hello@fortis.ph">hello@fortis.ph</a></div></div></div><form className="contact-form" onSubmit={e => e.preventDefault()}><div className="form-heading"><span className="label">START A CONVERSATION</span><h2>Tell us about<br />your next move.</h2></div><label>Your name<input required placeholder="Juan Dela Cruz" /></label><label>Work email<input required type="email" placeholder="juan@company.com" /></label><label>Service needed<select defaultValue=""><option value="" disabled>Select a capability</option>{services.map(service => <option key={service.title}>{service.title}</option>)}</select></label><label>What can we help you protect?<textarea rows="4" placeholder="A little context helps us prepare..." /></label><label className="checkbox"><input type="checkbox" /> This is an urgent inquiry</label><button className="button" type="submit">Send enquiry <ArrowRight size={16} /></button></form></section></> }
function Clients() { const names = ['AYALA', 'SM PRIME', 'GLOBE', 'JOLLIBEE', 'ROBINSONS', 'MERALCO', 'SAN MIGUEL', 'UNIONBANK']; const reversedNames = [...names].reverse(); return <><PageIntro eyebrow="TRUSTED BY" title={<>The company we keep<br /><em>keeps us sharp.</em></>} copy="From national institutions to fast-moving teams, Solimon is the quiet confidence behind ambitious work." /><section className="clients-hero"><div className="wrap"><div className="client-quote"><span className="quote-mark">“</span><blockquote>Solimon gave our people the confidence to focus on the work in front of us.</blockquote><span className="label">CHIEF OPERATING OFFICER · NATIONAL RETAIL GROUP</span></div></div></section><section className="marquee-section"><div className="marquee-track marquee-track-left">{[...names, ...names].map((name, i) => <div className="client-logo" key={`top-${name}-${i}`}><span>{name.slice(0, 1)}</span>{name}</div>)}</div><div className="marquee-track marquee-track-right">{[...reversedNames, ...reversedNames].map((name, i) => <div className="client-logo" key={`bottom-${name}-${i}`}><span>{name.slice(0, 1)}</span>{name}</div>)}</div></section><section className="wrap client-bottom"><Eyebrow>BUILT FOR COMPLEXITY</Eyebrow><h2>Security is not a vendor line.<br /><em>It is a relationship.</em></h2><Button to="/contact">Become a Solimon client</Button></section></> }
function Donations() { const [amount, setAmount] = useState(1000); return <><section className="donation-hero" style={{ backgroundImage: `linear-gradient(90deg, rgba(9,13,22,.97) 20%, rgba(9,13,22,.6), rgba(9,13,22,.2)), url(${images.community})` }}><div className="wrap"><Eyebrow>SOLIMON COMMUNITY FUND</Eyebrow><h1>For the ones<br /><em>who stand watch.</em></h1><p>Supporting the families of fallen security personnel and safer communities across the Philippines.</p><div className="fund-progress"><div><span>PHP 3,840,000 raised</span><span>PHP 5,000,000 goal</span></div><i><b style={{ width: '77%' }} /></i><small>77% of this year's community goal</small></div></div></section><section className="wrap donation-panel"><div><Eyebrow>MAKE A DIFFERENCE</Eyebrow><h2>Your support has<br /><em>real reach.</em></h2><p>100% of contributions go to family assistance, education grants and community safety projects.</p></div><div className="donation-form"><span className="label">CHOOSE AN AMOUNT</span><div className="amounts">{[500, 1000, 2500].map(value => <button className={amount === value ? 'active' : ''} onClick={() => setAmount(value)} key={value}>PHP {value.toLocaleString()}</button>)}<button className={![500, 1000, 2500].includes(amount) ? 'active' : ''} onClick={() => setAmount(0)}>CUSTOM</button></div>{amount === 0 && <input type="number" placeholder="Enter amount in PHP" onChange={e => setAmount(Number(e.target.value))} />}<button className="button support-button">Support {amount ? `PHP ${amount.toLocaleString()}` : 'our heroes'} <ArrowRight size={16} /></button><div className="payment-options"><span>SECURE PAYMENT VIA</span><b>GCash</b><b>Maya</b><b>VISA</b></div></div></section></> }
function Footer() { return <footer className="site-footer"><div className="wrap footer-grid"><div><Link to="/" className="brand"><span className="brand-mark"><Shield size={19} /></span><span><b>SOLIMON</b><small>SECURITY</small></span></Link><p>Security with conviction.<br />Built for the Philippines.</p></div><div><span className="label">EXPLORE</span><Link to="/services">Services</Link><Link to="/about">About us</Link><Link to="/careers">Careers</Link></div><div><span className="label">CONNECT</span><Link to="/contact">Contact</Link><a href="mailto:hello@fortis.ph">hello@fortis.ph</a><a href="tel:+63288885555">+63 2 8888 5555</a></div><div><span className="label">FOLLOW THE SIGNAL</span><div className="socials"><a href="#instagram">IG</a><a href="#linkedin">in</a><a href="#facebook">f</a></div></div></div><div className="wrap footer-bottom"><span>© 2026 Solimon Security Group</span><span>Licensed and operating nationwide</span></div></footer> }
export default function Root() { return <BrowserRouter><App /></BrowserRouter> }
