import React, { useEffect, useRef, useState } from 'react'
import { ArrowDown, ArrowUpRight, Check, Search, ShoppingBag } from 'lucide-react'
import { createRoot } from 'react-dom/client'
import './styles.css'

const products = [
  { name: 'Sun Field Bed', type: 'Rest / 01', price: '$148', category: 'Rest', image: 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&w=1000&q=88' },
  { name: 'River Bowl', type: 'Ritual / 02', price: '$58', category: 'Ritual', image: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=1000&q=88' },
  { name: 'Longway Lead', type: 'Outside / 03', price: '$46', category: 'Outside', image: 'https://images.unsplash.com/photo-1601758174114-e711c0cbaa69?auto=format&fit=crop&w=1000&q=88' },
  { name: 'Dune Throw', type: 'Rest / 04', price: '$84', category: 'Rest', image: 'https://images.unsplash.com/photo-1558788353-f76d92427f16?auto=format&fit=crop&w=1000&q=88' },
  { name: 'Ember Ball', type: 'Play / 05', price: '$24', category: 'Play', image: 'https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?auto=format&fit=crop&w=1000&q=88' },
  { name: 'Path Towel', type: 'Outside / 06', price: '$34', category: 'Outside', image: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&w=1000&q=88' },
  { name: 'Tide Mat', type: 'Ritual / 07', price: '$72', category: 'Ritual', image: 'https://images.unsplash.com/photo-1581888227599-779811939961?auto=format&fit=crop&w=1000&q=88' },
  { name: 'Cinder Toy', type: 'Play / 08', price: '$28', category: 'Play', image: 'https://images.unsplash.com/photo-1596492784531-6e6eb5ea9993?auto=format&fit=crop&w=1000&q=88' },
]
const slug = (product) => product.name.toLowerCase().replaceAll(' ', '-')

function Header({ bagCount, onSearch }) { return <header className="site-header"><a className="brand" href="#top">cairn<span>/05</span></a><nav><a href="#/store">Store</a><a href="#about">About</a></nav><div className="header-tools"><button aria-label="Search" onClick={onSearch}><Search size={17} /></button><button aria-label="Shopping bag"><ShoppingBag size={17} /><b>{bagCount}</b></button></div></header> }

function ProductCard({ product, onAdd }) { return <article className="product-card"><a className="product-image" href={`#${slug(product)}`}><img src={product.image} alt={product.name} /><span>View piece <ArrowUpRight size={15} /></span></a><div className="product-meta"><div><small>{product.type}</small><h2>{product.name}</h2></div><strong>{product.price}</strong></div><button className="add-button" onClick={() => onAdd(product)}>Add to bag <ArrowUpRight size={15} /></button></article> }

function FilmStrip({ items, direction, progress }) { const frames = [...items, ...items]; const details = [{ title: 'Made for the in-between', copy: 'Useful forms for the quiet rituals of a shared life.' }, { title: 'A slower way through', copy: 'Materials, movement, and objects with room to breathe.' }, { title: 'Field note / 05', copy: 'The collection keeps moving. Stay with the frame.' }]; return <div className={`film-strip film-strip-${direction}`} style={{ '--strip-progress': progress }}><div className="film-track">{frames.map((product, index) => <React.Fragment key={`${direction}-${index}`}><a className="film-frame" href={`#${slug(product)}`}><img src={product.image} alt={product.name} /><span>{product.type}</span></a>{index % 4 === 1 && <div className="film-frame film-copy"><small>{details[((index % items.length) / 4) % details.length | 0].title}</small><strong>{details[((index % items.length) / 4) % details.length | 0].copy}</strong><span>cairn / 05</span></div>}</React.Fragment>)}</div></div> }

function Scenery({ progress }) { return <div className="scenery" aria-hidden="true"><div className="scenery-horizon" /><div className="scenery-ridge ridge-near" /><div className="scenery-ridge ridge-far" /><div className="scenery-sun" /><div className="scenery-grain" /></div> }

function Storefront({ progress }) { return <main className="storefront" id="top" style={{ '--scroll-progress': progress }}><Scenery progress={progress} /><div className="storefront-film film-chapter"><div className="film-stage"><FilmStrip items={products} direction="right" progress={progress} /><div className="film-centerline"><span>Cairn / 05</span><strong>Keep moving</strong></div><FilmStrip items={[...products].reverse()} direction="left" progress={progress} /><FilmStrip items={products} direction="right" progress={progress} /></div></div></main> }

function StorePage({ bagCount, onAdd, onSearch }) { const [category, setCategory] = useState('All'); const [query, setQuery] = useState(''); const categories = ['All', 'Rest', 'Ritual', 'Outside', 'Play']; const visible = products.filter((product) => (category === 'All' || product.category === category) && `${product.name} ${product.type} ${product.category}`.toLowerCase().includes(query.toLowerCase().trim())); return <main className="store-page" id="store"><div className="store-page-intro"><div><p className="eyebrow">The cairn store / 05</p><h1>Find your<br /><i>own rhythm.</i></h1></div><p>Useful objects, easy to browse. The scenery can wait while you find the right piece.</p><a href="#top"><ArrowUpRight size={15} /> Back to storefront</a></div><div className="catalog-toolbar store-toolbar"><label className="search-field store-search"><Search size={14} /><input id="catalog-search" type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search pieces" aria-label="Search pieces" /></label><div className="category-tabs">{categories.map((item) => <button className={category === item ? 'selected' : ''} key={item} onClick={() => setCategory(item)}>{item}</button>)}</div><span className="catalog-count">{String(visible.length).padStart(2, '0')} pieces</span></div><div className="catalog-heading store-catalog-heading"><p>Collection / {category}</p><span>08 pieces / 2025</span></div>{visible.length ? <div className="product-grid">{visible.map((product) => <ProductCard product={product} onAdd={onAdd} key={product.name} />)}</div> : <div className="empty-state"><h2>No pieces here yet.</h2><button onClick={() => { setQuery(''); setCategory('All') }}>Reset collection</button></div>}</main> }

function ItemPage({ product, onAdd }) { const productIndex = products.findIndex((item) => item.name === product.name); const gallery = [0, 1, 2, 3].map((offset) => products[(productIndex + offset) % products.length]); return <main className="item-page"><div className="item-page-top"><a href="#/store"><ArrowUpRight size={15} /> Back to store</a><span>Archive / {product.type}</span></div><div className="item-layout"><div className="item-gallery" aria-label={`${product.name} photo gallery`}>{gallery.map((image, index) => <figure className={`item-photo item-photo-${index + 1}`} key={`${product.name}-${index}`}><img src={image.image} alt={index === 0 ? product.name : `${product.name} detail ${index}`} /><figcaption>{String(index + 1).padStart(2, '0')} / 04</figcaption></figure>)}</div><section className="item-details"><p className="eyebrow">{product.type}</p><h1>{product.name}</h1><p className="item-description">A useful object for the slower parts of a shared day. Made to be handled, moved, and lived with.</p><div className="item-purchase"><strong>{product.price}</strong><button className="add-button" onClick={() => onAdd(product)}>Add to bag <ArrowUpRight size={15} /></button></div><p className="item-note">Photographed in the field / cairn archive 05</p></section></div></main> }

function App() { const [hash, setHash] = useState(window.location.hash); const [bagCount, setBagCount] = useState(0); const [notice, setNotice] = useState(''); const [progress, setProgress] = useState(0); const storeRoute = hash === '#/store'; const itemProduct = products.find((product) => hash === `#${slug(product)}`); const addToBag = (product) => { setBagCount((count) => count + 1); setNotice(`${product.name} added to bag`); setTimeout(() => setNotice(''), 2200) }; useEffect(() => { const update = () => setHash(window.location.hash); addEventListener('hashchange', update); return () => removeEventListener('hashchange', update) }, []); useEffect(() => { document.body.classList.remove('film-scroll-lock'); const update = () => setProgress(Math.min(1, Math.max(0, window.scrollY / Math.max(1, document.body.scrollHeight - window.innerHeight)))); addEventListener('scroll', update, { passive: true }); update(); return () => removeEventListener('scroll', update) }, [storeRoute, itemProduct]); return <><Header bagCount={bagCount} onSearch={() => document.getElementById('catalog-search')?.focus()} />{itemProduct ? <ItemPage product={itemProduct} onAdd={addToBag} /> : storeRoute ? <StorePage bagCount={bagCount} onAdd={addToBag} /> : <Storefront progress={progress} />}{notice && <div className="toast"><Check size={15} />{notice}</div>}</> }

createRoot(document.getElementById('root')).render(<App />)
